mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root

postgres:
  image: postgres

sut:
  image: node:4-alpine
  command: >
    sh -c '
      apk add --no-cache make python g++ \
      && npm config set loglevel error \
      && npm i npm@latest -g \
      && cd /app \
      && npm i \
      && npm i sequelize@${SEQUELIZE_VERSION} \
      && npm t'
  volumes:
    - .:/app
  links:
    - mysql
    - postgres
